{{- if and .Values.enabled .Values.storage.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.storage.claimName }}
  annotations:
    argocd.argoproj.io/sync-options: Delete=false
  labels:
    app.kubernetes.io/name: {{ .Values.api.name }}
    app.kubernetes.io/part-of: {{ .Values.partOf }}
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: {{ .Values.storage.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.storage.storageSize }}
{{- end }}
